"""empty message

Revision ID: 16656c9be87
Revises: None
Create Date: 2015-04-03 11:09:17.925707

"""

# revision identifiers, used by Alembic.
revision = '16656c9be87'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
