"""creation_date for user

Revision ID: 2fd4d9c4089
Revises: 1b569315064
Create Date: 2015-04-03 11:29:34.099493

"""

# revision identifiers, used by Alembic.
revision = '2fd4d9c4089'
down_revision = '1b569315064'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creation_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'creation_date')
    ### end Alembic commands ###
