"""empty message

Revision ID: 4f10b100fbf
Revises: 2fd4d9c4089
Create Date: 2015-04-03 11:38:57.333642

"""

# revision identifiers, used by Alembic.
revision = '4f10b100fbf'
down_revision = '2fd4d9c4089'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_field', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_field')
    ### end Alembic commands ###
