"""empty message

Revision ID: a86f36181e
Revises: 4f10b100fbf
Create Date: 2015-04-03 11:43:46.847482

"""

# revision identifiers, used by Alembic.
revision = 'a86f36181e'
down_revision = '4f10b100fbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_field2', sa.String(length=10), server_default='tmp', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_field2')
    ### end Alembic commands ###
